class Commands:
    LEECH = "leech@UnnamedKKbot"
    PURGE = "purge@UnnamedKKbot"
    PAUSEALL = "pauseall@UnnamedKKbot"
    RESUMEALL = "resumeall@UnnamedKKbot"
    STATUS = "status@UnnamedKKbot"
    SETTINGS = "settings@UnnamedKKbot"
    EXEC = "exec@UnnamedKKbot"
    UPLOAD = "upload@UnnamedKKbot"
    YTDL = "ytdl@UnnamedKKbot"
    PYTDL = "pytdl@UnnamedKKbot"
    ABOUT = "about@UnnamedKKbot"
    GETLOGS = "getlogs@UnnamedKKbot"
    SERVER = "server@UnnamedKKbot"
    USERSETTINGS = "usetting@UnnamedKKbot"
    INSTADL = "instadl@UnnamedKKbot"
